import { readFile, stat } from 'node:fs/promises';
import { basename, join, relative } from 'node:path';
import { ForbiddenException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { APP_CONFIG, type AppConfig } from '../config/configuration.js';
import { resolveWithinRoots } from '../security/path-guard.js';
import { METADATA_STORE, type MetadataStore } from '../common/metadata-store.js';
import { isSensitivePath, sensitivePathReason } from '../security/secret-files.js';
import { redactSecrets } from '../security/secret-values.js';
import { detectLanguage } from '../indexing/chunker.js';
import { extractImport, extractSymbol } from './outline.js';
import { VectorStoreService } from '../vector/vector-store.service.js';
import type {
  ExplainFileInput,
  ExplainFileResult,
  FileSymbol,
  GenerateSnippetInput,
  GenerateSnippetResult,
  SearchCodeInput,
  SearchCodeResult,
} from '@ai-code-companion/contracts';

type SnippetTemplate = (prompt: string) => string;

// Data, not logic: every entry is a survivable mutant that no sensible test would
// pin down, and there are enough of them to swamp the file's mutation score.
// Stryker disable all

const SNIPPET_TEMPLATES: Readonly<Record<string, SnippetTemplate | undefined>> = {
  typescript: (prompt) => `/**
 * ${prompt}
 */
export async function run(input: string): Promise<string> {
  // TODO: implement — generated by generate_snippet (stub model).
  return input;
}
`,
  javascript: (prompt) => `/**
 * ${prompt}
 */
export async function run(input) {
  // TODO: implement — generated by generate_snippet (stub model).
  return input;
}
`,
  python: (prompt) => `def run(value: str) -> str:
    """${prompt}"""
    # TODO: implement - generated by generate_snippet (stub model).
    return value
`,
  rust: (prompt) => `/// ${prompt}
pub fn run(input: &str) -> String {
    // TODO: implement - generated by generate_snippet (stub model).
    input.to_string()
}
`,
  go: (prompt) => `// Run ${prompt}
func Run(input string) (string, error) {
	// TODO: implement - generated by generate_snippet (stub model).
	return input, nil
}
`,
};

// Stryker restore all

const MAX_EXPLAIN_BYTES = 512 * 1024;

/**
 * The single implementation behind the three MCP tools. It is deliberately free
 * of MCP and LangChain types so it can be exposed through both transports (and
 * unit-tested on its own).
 */
@Injectable()
export class CodeToolsService {
  constructor(
    @Inject(APP_CONFIG) private readonly config: AppConfig,
    private readonly vectorStore: VectorStoreService,
    @Inject(METADATA_STORE) private readonly metadata: MetadataStore,
  ) {}

  /**
   * Resolves the path `explain_file` was given, including the ones `search_code`
   * hands out.
   *
   * Those are relative to the *indexed root* — `security/local-access.ts` for a
   * root of `backend/src` — because that is what reads well in a citation. But
   * resolution is relative to the process's working directory, which for a
   * packaged app is wherever the OS happened to start it, so a model that
   * faithfully copied a path out of its own search results got "Path does not
   * exist" every time. Measured: three questions, three correct files found by
   * retrieval, three failures here, and the tool's error became the answer.
   *
   * So the roots are tried too. Every candidate still goes through
   * `resolveWithinRoots`, which is what enforces the allow-list and resolves
   * symlinks before checking containment — this widens the vocabulary, not the
   * boundary.
   */
  private async resolveExplainPath(inputPath: string): Promise<string> {
    const { allowedRoots } = this.config.indexing;
    try {
      return await resolveWithinRoots(inputPath, allowedRoots, 'file');
    } catch (error) {
      // Only a path that is not there is worth a second guess. A file that exists
      // but sits outside the allow-list, or is a directory, has been answered.
      if (!(error instanceof NotFoundException)) throw error;

      for (const root of await this.metadata.listRoots()) {
        try {
          return await resolveWithinRoots(join(root.path, inputPath), allowedRoots, 'file');
        } catch {
          // Try the next root; the original error is thrown below if none match.
        }
      }
      throw error;
    }
  }

  async searchCode(input: SearchCodeInput): Promise<SearchCodeResult> {
    const matches = await this.vectorStore.search(input.query, {
      limit: input.limit ?? 5,
      root: input.root,
    });

    return {
      query: input.query,
      // An index built before the walker learned this rule can still hold secrets,
      // and re-indexing is the user's choice, not ours. Filter on the way out too.
      matches: matches
        .filter((match) => !isSensitivePath(match.metadata.path))
        .map((match) => ({
          path: match.metadata.path,
          relativePath: match.metadata.relativePath,
          language: match.metadata.language,
          startLine: match.metadata.startLine,
          endLine: match.metadata.endLine,
          score: Number(match.score.toFixed(4)),
          // Again on the way out, for the same reason the path filter is: an index
          // built before this existed still holds whatever it held, and re-indexing
          // is the user's choice rather than ours.
          text: redactSecrets(match.text, { entropyScan: this.config.secrets.entropyScan }).text,
        })),
    };
  }

  async explainFile(input: ExplainFileInput): Promise<ExplainFileResult> {
    const path = await this.resolveExplainPath(input.path);
    // Checked on the *resolved* path, so a symlink cannot launder ~/.ssh/id_rsa
    // into an innocuous-looking name inside the repo.
    if (isSensitivePath(path)) throw new ForbiddenException(sensitivePathReason(input.path));

    // stat before read: reading a multi-gigabyte file into memory just to reject
    // it afterwards is how a "too large" guard becomes an OOM.
    const { size } = await stat(path);
    if (size > MAX_EXPLAIN_BYTES) {
      throw new Error(`File is too large to explain (${size} bytes, limit ${MAX_EXPLAIN_BYTES})`);
    }

    const raw = await readFile(path);
    const content = raw.toString('utf8');
    const lines = content.split(/\r?\n/);
    const language = detectLanguage(path);

    const imports = new Set<string>();
    const symbols: FileSymbol[] = [];

    lines.forEach((rawLine, index) => {
      // Trimmed once so neither extractor needs a leading `\s*`, which is what makes
      // this family of patterns backtrack quadratically.
      const line = rawLine.trim();

      const specifier = extractImport(line);
      if (specifier !== undefined) imports.add(specifier);

      const symbol = extractSymbol(line);
      if (symbol !== undefined) symbols.push({ ...symbol, line: index + 1 });
    });

    return {
      path,
      language,
      lineCount: lines.length,
      byteSize: raw.byteLength,
      imports: [...imports],
      symbols,
      summary: this.summarise(path, language, lines.length, imports.size, symbols),
    };
  }

  /** Mocked generator: templates, not a model. Swap in the LLM to make it real. */
  async generateSnippet(input: GenerateSnippetInput): Promise<GenerateSnippetResult> {
    const language = (input.language ?? 'typescript').toLowerCase();
    const template = SNIPPET_TEMPLATES[language];

    return {
      language,
      code: template
        ? template(input.prompt)
        : `// ${language}\n// ${input.prompt}\n// TODO: implement — generated by generate_snippet (stub model).\n`,
      notes: template
        ? 'Template-generated scaffold. Wire an LLM into generateSnippet() for real synthesis.'
        : `No template for "${language}" yet; returned a generic scaffold.`,
    };
  }

  private summarise(
    path: string,
    language: string,
    lineCount: number,
    importCount: number,
    symbols: readonly FileSymbol[],
  ): string {
    const root = this.config.indexing.allowedRoots.find((candidate) => path.startsWith(candidate));
    const label = root ? relative(root, path) || basename(path) : basename(path);

    if (symbols.length === 0) {
      return `${label} is a ${lineCount}-line ${language} file with ${importCount} import(s) and no top-level declarations detected.`;
    }

    const byKind = new Map<string, string[]>();
    for (const symbol of symbols) {
      byKind.set(symbol.kind, [...(byKind.get(symbol.kind) ?? []), symbol.name]);
    }
    const parts = [...byKind.entries()].map(
      ([kind, names]) =>
        `${names.length} ${kind}${names.length === 1 ? '' : 's'} (${names.slice(0, 5).join(', ')}${names.length > 5 ? ', …' : ''})`,
    );

    return `${label} is a ${lineCount}-line ${language} file with ${importCount} import(s), declaring ${parts.join(', ')}.`;
  }
}
