import { readFile } from 'node:fs/promises';
import { basename, relative } from 'node:path';
import { Inject, Injectable } from '@nestjs/common';
import { APP_CONFIG, type AppConfig } from '../config/configuration.js';
import { resolveWithinRoots } from '../common/path-guard.js';
import { detectLanguage } from '../indexing/chunker.js';
import { VectorStoreService } from '../vector/vector-store.service.js';
import type {
  ExplainFileInput,
  ExplainFileResult,
  FileSymbol,
  GenerateSnippetInput,
  GenerateSnippetResult,
  SearchCodeInput,
  SearchCodeResult,
} from './tool-schemas.js';

/**
 * Cheap, language-agnostic outline extraction. A real product would use
 * tree-sitter here; regexes keep the demo dependency-free and deterministic,
 * which is exactly what the unit tests want.
 */
const SYMBOL_PATTERNS: ReadonlyArray<{ kind: string; pattern: RegExp }> = [
  { kind: 'class', pattern: /^\s*(?:export\s+)?(?:abstract\s+)?class\s+([A-Za-z_$][\w$]*)/ },
  { kind: 'interface', pattern: /^\s*(?:export\s+)?interface\s+([A-Za-z_$][\w$]*)/ },
  { kind: 'type', pattern: /^\s*(?:export\s+)?type\s+([A-Za-z_$][\w$]*)\s*[=<]/ },
  { kind: 'enum', pattern: /^\s*(?:export\s+)?enum\s+([A-Za-z_$][\w$]*)/ },
  { kind: 'function', pattern: /^\s*(?:export\s+)?(?:async\s+)?function\s+\*?\s*([A-Za-z_$][\w$]*)/ },
  { kind: 'function', pattern: /^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=\s*(?:async\s*)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>/ },
  { kind: 'function', pattern: /^\s*(?:pub\s+)?(?:async\s+)?fn\s+([A-Za-z_][\w]*)/ },
  { kind: 'function', pattern: /^\s*func\s+(?:\([^)]*\)\s*)?([A-Za-z_][\w]*)/ },
  { kind: 'function', pattern: /^\s*(?:async\s+)?def\s+([A-Za-z_][\w]*)/ },
  { kind: 'class', pattern: /^\s*(?:pub\s+)?struct\s+([A-Za-z_][\w]*)/ },
];

const IMPORT_PATTERNS: ReadonlyArray<RegExp> = [
  /^\s*import\s+(?:.+?\s+from\s+)?['"]([^'"]+)['"]/,
  /^\s*(?:const|let|var)\s+.+?=\s*require\(\s*['"]([^'"]+)['"]\s*\)/,
  /^\s*from\s+([\w.]+)\s+import\s+/,
  /^\s*use\s+([\w:]+)/,
];

type SnippetTemplate = (prompt: string) => string;

const SNIPPET_TEMPLATES: Readonly<Record<string, SnippetTemplate | undefined>> = {
  typescript: (prompt) => `/**
 * ${prompt}
 */
export async function run(input: string): Promise<string> {
  // TODO: implement — generated by generate_snippet (stub model).
  return input;
}
`,
  javascript: (prompt) => `/**
 * ${prompt}
 */
export async function run(input) {
  // TODO: implement — generated by generate_snippet (stub model).
  return input;
}
`,
  python: (prompt) => `def run(value: str) -> str:
    """${prompt}"""
    # TODO: implement - generated by generate_snippet (stub model).
    return value
`,
  rust: (prompt) => `/// ${prompt}
pub fn run(input: &str) -> String {
    // TODO: implement - generated by generate_snippet (stub model).
    input.to_string()
}
`,
  go: (prompt) => `// Run ${prompt}
func Run(input string) (string, error) {
	// TODO: implement - generated by generate_snippet (stub model).
	return input, nil
}
`,
};

const MAX_EXPLAIN_BYTES = 512 * 1024;

/**
 * The single implementation behind the three MCP tools. It is deliberately free
 * of MCP and LangChain types so it can be exposed through both transports (and
 * unit-tested on its own).
 */
@Injectable()
export class CodeToolsService {
  constructor(
    @Inject(APP_CONFIG) private readonly config: AppConfig,
    private readonly vectorStore: VectorStoreService,
  ) {}

  async searchCode(input: SearchCodeInput): Promise<SearchCodeResult> {
    const matches = await this.vectorStore.search(input.query, {
      limit: input.limit ?? 5,
      root: input.root,
    });

    return {
      query: input.query,
      matches: matches.map((match) => ({
        path: match.metadata.path,
        relativePath: match.metadata.relativePath,
        language: match.metadata.language,
        startLine: match.metadata.startLine,
        endLine: match.metadata.endLine,
        score: Number(match.score.toFixed(4)),
        text: match.text,
      })),
    };
  }

  async explainFile(input: ExplainFileInput): Promise<ExplainFileResult> {
    const path = await resolveWithinRoots(
      input.path,
      this.config.indexing.allowedRoots,
      'file',
    );
    const raw = await readFile(path);
    if (raw.byteLength > MAX_EXPLAIN_BYTES) {
      throw new Error(`File is too large to explain (${raw.byteLength} bytes)`);
    }

    const content = raw.toString('utf8');
    const lines = content.split(/\r?\n/);
    const language = detectLanguage(path);

    const imports = new Set<string>();
    const symbols: FileSymbol[] = [];

    lines.forEach((line, index) => {
      for (const pattern of IMPORT_PATTERNS) {
        const match = pattern.exec(line);
        if (match) {
          imports.add(match[1]);
          break;
        }
      }
      for (const { kind, pattern } of SYMBOL_PATTERNS) {
        const match = pattern.exec(line);
        if (match) {
          symbols.push({ kind, name: match[1], line: index + 1 });
          break;
        }
      }
    });

    return {
      path,
      language,
      lineCount: lines.length,
      byteSize: raw.byteLength,
      imports: [...imports],
      symbols,
      summary: this.summarise(path, language, lines.length, imports.size, symbols),
    };
  }

  /** Mocked generator: templates, not a model. Swap in the LLM to make it real. */
  async generateSnippet(input: GenerateSnippetInput): Promise<GenerateSnippetResult> {
    const language = (input.language ?? 'typescript').toLowerCase();
    const template = SNIPPET_TEMPLATES[language];

    return {
      language,
      code: template
        ? template(input.prompt)
        : `// ${language}\n// ${input.prompt}\n// TODO: implement — generated by generate_snippet (stub model).\n`,
      notes: template
        ? 'Template-generated scaffold. Wire an LLM into generateSnippet() for real synthesis.'
        : `No template for "${language}" yet; returned a generic scaffold.`,
    };
  }

  private summarise(
    path: string,
    language: string,
    lineCount: number,
    importCount: number,
    symbols: readonly FileSymbol[],
  ): string {
    const root = this.config.indexing.allowedRoots.find((candidate) => path.startsWith(candidate));
    const label = root ? relative(root, path) || basename(path) : basename(path);

    if (symbols.length === 0) {
      return `${label} is a ${lineCount}-line ${language} file with ${importCount} import(s) and no top-level declarations detected.`;
    }

    const byKind = new Map<string, string[]>();
    for (const symbol of symbols) {
      byKind.set(symbol.kind, [...(byKind.get(symbol.kind) ?? []), symbol.name]);
    }
    const parts = [...byKind.entries()].map(
      ([kind, names]) =>
        `${names.length} ${kind}${names.length === 1 ? '' : 's'} (${names.slice(0, 5).join(', ')}${names.length > 5 ? ', …' : ''})`,
    );

    return `${label} is a ${lineCount}-line ${language} file with ${importCount} import(s), declaring ${parts.join(', ')}.`;
  }
}
